notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/T047SFFHY
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
    
language: elixir
elixir:
  - 1.6.0
otp_release: 20.0

env:
  - MIX_ENV=test

script: mix coveralls.travis
